config/routes.rb
Prognozi::Application.routes.draw do
  root to: 'predictions#index'

  devise_for :users, only: [:sessions]

  as :user do
    post 'users/sign_up' => 'devise/registrations#create', as: :new_user_registration
  end

  match '/predictions'     => 'predictions#index',   via: :get
  match '/match_prediction' => 'predictions#match',  via: :post
  match '/group_prediction' => 'predictions#group',  via: :post
  match '/top_scorer_prediction' => 'predictions#top_scorer',  via: :post

  match '/load_group_stage' => 'predictions#load_group_stage',  via: :get

  match '/load_knockout_stage' => 'predictions#load_knockout_stage',  via: :get
  match '/save_knockout_stage' => 'predictions#save_knockout_stage',  via: :post

  match '/standings'     => 'participants#ranking',   via: :get
  match '/scoring'     => 'participants#scoring',   via: :get
  match '/rules'     => 'participants#rules',   via: :get

  # match '/decline_invitation'           => 'rooms#room_inv_decline',   via: :post
  # match '/accept_invitation'            => 'rooms#room_inv_accept',    via: :post
  # match '/roominvites/:room_id/:uids'   => 'rooms#invite',             via: :get
  # match '/newroom'                => 'rooms#new',      via: :get
  # match '/createroom'             => 'rooms#create',   via: :post
  # match '/rooms'                  => 'rooms#index',    via: :get
  # match '/rooms/:room_id'         => 'rooms#show',     via: :get, as: :room

  #Facebook auth

  # match 'auth/:provider/callback', to: 'sessions#oauth_success'
  # match 'auth/failure', to: redirect('/')

  match '/results/:token'       => 'results#index',   via: :get
  match '/load_group_results'   => 'results#load_group_stage',   via: :get

  match '/dev'     => 'predictions#dev',   via: :get
  match '/points'  => 'predictions#points',   via: :get

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_filter :authenticate_user!, except: [:points, :dev]

  def dev
    @groups = Group.where(tournament_id: $current_tournament)
  end

  def index
    # redirect_to controller: :results, action: :index, token: current_user.token and return

    @groups = Group.where(tournament_id: $current_tournament)
  end

  def match
    if params[:prediction].present?
      params[:prediction].each do |match, prog|
        pred = MatchPrediction.find_or_initialize_by(match_id: match, user_id: current_user.id)
        pred.sign = prog[:sign] if prog[:sign].present?
        pred.host_score = prog[:host] if prog[:host].present?
        pred.guest_score = prog[:guest] if prog[:guest].present?
        pred.save
      end
    end
    render nothing: true
  end

  def group
    puts params[:prediction]
    if params[:prediction].present?
      params[:prediction].each do |group_code, standing|
        group_id = Group.find_by(name: group_code).id
        GroupStandingPrediction.where(group_id: group_id, user_id: current_user.id).delete_all
        group_teams = GroupStanding.where(group_id: group_id).pluck(:team_id)
        ef = Elimination.find_by_code('ef')
        EliminationPrediction.where(user_id: current_user.id, elimination_id: ef.id, team_id: group_teams).delete_all

        GroupStandingPrediction.create(group_id: group_id, user_id: current_user.id, position: 1, team_id: standing[:winner])
        GroupStandingPrediction.create(group_id: group_id, user_id: current_user.id, position: 2, team_id: standing[:runner_up])
        GroupStandingPrediction.create(group_id: group_id, user_id: current_user.id, position: 3, team_id: standing[:third])
        GroupStandingPrediction.create(group_id: group_id, user_id: current_user.id, position: 4, team_id: standing[:last])

        # EliminationPrediction.create(user_id: current_user.id, elimination_id: ef.id, team_id: standing[:winner])
        # EliminationPrediction.create(user_id: current_user.id, elimination_id: ef.id, team_id: standing[:runner_up])
      end
    end
    render nothing: true
  end

  def load_group_stage
    user_id = params[:user_id].to_i > 0 ? params[:user_id] : current_user.id
    all_groups = Group.where(tournament_id: $current_tournament)
    groups = {}
    Match.group_games.joins("LEFT OUTER JOIN match_predictions ON match_predictions.match_id = matches.id AND match_predictions.user_id = #{user_id}")
          .joins('INNER JOIN teams AS hosts ON hosts.id = matches.host_id')
          .joins('INNER JOIN teams AS guests ON guests.id = matches.guest_id')
          .order("matches.start_at")
          .select("match_predictions.host_score host_prediction, match_predictions.guest_score guest_prediction, hosts.name host_team, hosts.flag host_flag, guests.name guest_team, guests.flag guest_flag, matches.id, matches.start_at, matches.code, matches.phase_id")
          .to_a.group_by(&:phase_id)
    .each do |group_id, matches|
      group_name = all_groups.detect{ |x| x.id == group_id}.name
      groups[group_name] = {} if groups[group_name].blank?
      groups[group_name][:matches] = matches
    end

    groups.each do |group_name, matches|
      group_id = all_groups.detect{ |x| x.name == group_name}.id
      groups[group_name][:teams] = Team.joins(:group_standing).where('group_standings.group_id' => group_id)
                                       .select("group_standings.position official_position, teams.*")
    end

    render json: groups
  end

  def load_knockout_stage
    teams = {qf:[], sf:[], f:[], c: []}
    # current_user.group_standing_predictions
    #   .joins("INNER JOIN groups ON group_standing_predictions.group_id = groups.id")
    #   .joins("INNER JOIN teams ON group_standing_predictions.team_id = teams.id")
    #   .where('groups.tournament_id' => current_tournament.id)
    #   .select('groups.name group_name, teams.id team_id, teams.name team_name, position')
    # .each do |sp|
    #   if sp.position == 1 and
    #     teams[:last_16][:winners][sp.group_name] = {team_id: sp.team_id, team_name: sp.team_name}
    #   end
    #   if sp.position == 2
    #     teams[:last_16][:runners_up][sp.group_name] = {team_id: sp.team_id, team_name: sp.team_name}
    #   end
    # end

    current_user.elimination_predictions
      .joins('INNER JOIN teams ON elimination_predictions.team_id = teams.id')
      .joins("INNER JOIN eliminations ON elimination_predictions.elimination_id = eliminations.id AND eliminations.code IN ('qf','sf','f','c') AND eliminations.tournament_id = #{$current_tournament}")
      .select("teams.id team_id, teams.name team_name, eliminations.code stage")
    .each do |ep|
      teams[:qf] << {team_id: ep.team_id, team_name: ep.team_name} if ep.stage == 'qf'
      teams[:sf] << {team_id: ep.team_id, team_name: ep.team_name} if ep.stage == 'sf'
      teams[:f] << {team_id: ep.team_id, team_name: ep.team_name} if ep.stage == 'f'
      teams[:c] << {team_id: ep.team_id, team_name: ep.team_name} if ep.stage == 'c'
    end

    render json: teams
  end

  def save_knockout_stage
    qfe = Elimination.find_by(code: 'qf', tournament_id: $current_tournament).id
    sfe = Elimination.find_by(code: 'sf', tournament_id: $current_tournament).id
    fe = Elimination.find_by(code: 'f', tournament_id: $current_tournament).id
    ce = Elimination.find_by(code: 'c', tournament_id: $current_tournament).id
    current_user.elimination_predictions.where(elimination_id: [qfe, sfe, fe, ce]).delete_all

    if params[:qf].present?
      qf = params[:qf].split(',')
      qf.each do |team_id|
        current_user.elimination_predictions.create(team_id: team_id, elimination_id: qfe)
      end
    end

    if params[:sf].present?
      sf = params[:sf].split(',')
      sf.each do |team_id|
        current_user.elimination_predictions.create(team_id: team_id, elimination_id: sfe)
      end
    end

    if params[:f].present?
      f = params[:f].split(',')
      f.each do |team_id|
        current_user.elimination_predictions.create(team_id: team_id, elimination_id: fe)
      end
    end

    if params[:c].present?
      current_user.elimination_predictions.create(team_id: params[:c], elimination_id: ce)
    end

    render nothing: true
  end

  def top_scorer
    if params[:name].present?
      top_scorer_prediction = TopScorerPrediction.find_or_initialize_by(user_id: current_user.id, tournament_id: $current_tournament)
      top_scorer_prediction.name = params[:name]
      top_scorer_prediction.save
    end
    render nothing: true
  end
end

app/views/predictions/_group_predictions.slim
table.table-standard.table.table-bordered.table-striped.table-condensed.matches-predictions
  tr
    th Kick-off
    th Match
    th Result
    th Correct Score
  - group_predictions.each do |prediction|
    tr
      td = l prediction.start_at, format: :short
      td = prediction.name
      td
        = form_tag match_prediction_path, remote: true, method: :post
          = select_tag id="prediction[#{prediction.id}][sign]" , options_for_select([['1', '1'], ['X', 'X'], ['2', '2']], prediction.sign_prediction), {include_blank: true}
      td[style='height:20px']
        = form_tag match_prediction_path, remote: true, method: :post
          = select_tag id="prediction[#{prediction.id}][host]", options_for_select((0..8).map {|g| [g, g]},  prediction.host_prediction), {include_blank: prediction.host.name}
          | &nbsp;&nbsp;:&nbsp;&nbsp;
          = select_tag id="prediction[#{prediction.id}][guest]" , options_for_select((0..8).map {|g| [g, g]}, prediction.guest_prediction), {include_blank: prediction.host.name}

app/views/predictions/_group_standing_predictions.slim
table.table-standard.table.table-bordered.table-striped.table-condensed.standings-predictions[style='width:520px']
  tr
    th rel="tooltip" data-container="body" data-original-title='Position' Pos *
    th Team
    th rel="tooltip" data-container="body" data-original-title='Played' Pld
    th rel="tooltip" data-container="body" data-original-title='Wins' W
    th rel="tooltip" data-container="body" data-original-title='Draws' D
    th rel="tooltip" data-container="body" data-original-title='Loses' L
    th rel="tooltip" data-container="body" data-original-title='Goals For' GF
    th rel="tooltip" data-container="body" data-original-title='Goals Against' GA
    th rel="tooltip" data-container="body" data-original-title='Goal Difference' GD
    th rel="tooltip" data-container="body" data-original-title='Points' Pts

    tr[ng-repeat="team in groups['#{group.name}'].teams | orderBy : ['-points', 'tb' ,'-goal_difference', '-goals_for', '-coef']"
    ng-class="{'qualifies' : $index < 2 || ($index == 2 && third_standings.indexOf('#{group.name}') > -1)}"]
      td[style='height:20px;width:60px'] {{$index + 1}}
      td[style='height:20px;width:200px']
        span.flag_16.left_16[ng-class="{'{{team.flag}}_16_left' : true}"]
        | {{team.name}}
      td[style='height:20px;width:60px'] {{team.matches_played}}
      td[style='height:20px;width:60px'] {{team.matches_won}}
      td[style='height:20px;width:60px'] {{team.matches_drawn}}
      td[style='height:20px;width:60px'] {{team.matches_lost}}
      td[style='height:20px;width:60px'] {{team.goals_for}}
      td[style='height:20px;width:60px'] {{team.goals_against}}
      td[style='height:20px;width:60px'] {{team.goal_difference}}
      td[style='height:20px;width:60px'] {{team.points}}
p
  | * Team positions are calculated based on provided match results.
  br
  ol
    | Tie-break criteria are as follows:
    li Higher number of points obtained in the matches played between the teams in question
    li Superior goal difference resulting from the matches played between the teams in question
    li Higher number of goals scored in the matches played between the teams in question
    li Superior goal difference in all group matches
    li Higher number of goals scored in all group matches
    li Position in the UEFA national team coefficient ranking system.

app/views/predictions/_knockout_stage_predictions.slim
#brackets.brackets
  #b0.group5
    .r1
      div
        .bracketbox
          span.info (37)25 June – Saint-Étienne
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(37, last_16_top[1].team_id, last_16_top[1].team_name)"] {{last_16_top[1].team_name || '2nd A'}}
            - else
              span[] {{last_16_top[1].team_name || '2nd A'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(37, last_16_bottom[1].team_id, last_16_bottom[1].team_name)"] {{last_16_bottom[1].team_name || '2nd B'}}
            - else
              span[] {{last_16_bottom[1].team_name || '2nd B'}}
      div
        .bracketbox
          span.info (39)26 June – Lens
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(39, last_16_top[2].team_id, last_16_top[2].team_name)"] {{last_16_top[2].team_name || '1st D'}}
            - else
              span[] {{last_16_top[2].team_name || '1st D'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(39, last_16_bottom[2].team_id, last_16_bottom[2].team_name)"] {{last_16_bottom[2].team_name || '3rd B/E/F'}}
            - else
              span[] {{last_16_bottom[2].team_name || '3rd B/E/F'}}
      div
        .bracketbox
          span.info (38) 25 June – Paris
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(38, last_16_top[3].team_id, last_16_top[3].team_name)"] {{last_16_top[3].team_name || '1st B'}}
            - else
              span[] {{last_16_top[3].team_name || '1st B'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(38, last_16_bottom[3].team_id, last_16_bottom[3].team_name)"] {{last_16_bottom[3].team_name || '3rd A/C/D'}}
            - else
              span[] {{last_16_bottom[3].team_name || '3rd A/C/D'}}
      div
        .bracketbox
          span.info (42) 26 June – Toulouse
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(42, last_16_top[4].team_id, last_16_top[4].team_name)"] {{last_16_top[4].team_name || '1st F'}}
            - else
              span[] {{last_16_top[4].team_name || '1st F'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(42, last_16_bottom[4].team_id, last_16_bottom[4].team_name)"] {{last_16_bottom[4].team_name || '2nd E'}}
            - else
              span[] {{last_16_bottom[4].team_name || '2nd E'}}
      div
        .bracketbox
          span.info (41) 26 June – Lille
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(41, last_16_top[5].team_id, last_16_top[5].team_name)"] {{last_16_top[5].team_name || '1st C'}}
            - else
              span[] {{last_16_top[5].team_name || '1st C'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(41, last_16_bottom[5].team_id, last_16_bottom[5].team_name)"] {{last_16_bottom[5].team_name || '3rd A/B/F'}}
            - else
              span[] {{last_16_bottom[5].team_name || '3rd A/B/F'}}
      div
        .bracketbox
          span.info (43) 27 June – Saint-Denis
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(43, last_16_top[6].team_id, last_16_top[6].team_name)"] {{last_16_top[6].team_name || '1st E'}}
            - else
              span[] {{last_16_top[6].team_name || '1st E'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(43, last_16_bottom[6].team_id, last_16_bottom[6].team_name)"] {{last_16_bottom[6].team_name || '2nd D'}}
            - else
              span[] {{last_16_bottom[6].team_name || '2nd D'}}
      div
        .bracketbox
          span.info (40) 26 June – Lyon
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(40, last_16_top[7].team_id, last_16_top[7].team_name)"] {{last_16_top[7].team_name || '1st A'}}
            - else
              span[] {{last_16_top[7].team_name || '1st A'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(40, last_16_bottom[7].team_id, last_16_bottom[7].team_name)"] {{last_16_bottom[7].team_name || '3rd C/D/E'}}
            - else
              span[] {{last_16_bottom[7].team_name || '3rd C/D/E'}}
      div
        .bracketbox
          span.info (44) 27 June – Nice
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(44, last_16_top[8].team_id, last_16_top[8].team_name)"] {{last_16_top[8].team_name || '2nd B'}}
            - else
              span[] {{last_16_top[8].team_name || '2nd B'}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_qf(44, last_16_bottom[8].team_id, last_16_bottom[8].team_name)"] {{last_16_bottom[8].team_name || '2nd F'}}
            - else
              span[] {{last_16_bottom[8].team_name || '2nd F'}}

    .r2
      div
        .bracketbox
          span.info (45)30 June – Marseille
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(45, quarter_f[37].team_id, quarter_f[37].team_name)"] {{quarter_f[37].team_name}}
            - else
              span[] {{quarter_f[37].team_name}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(45, quarter_f[39].team_id, quarter_f[39].team_name)"] {{quarter_f[39].team_name}}
            - else
              span[] {{quarter_f[39].team_name}}
      div
        .bracketbox
          span.info (46)1 July – Lille
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(46, quarter_f[38].team_id, quarter_f[38].team_name)"] {{quarter_f[38].team_name}}
            - else
              span[] {{quarter_f[38].team_name}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(46, quarter_f[42].team_id, quarter_f[42].team_name)"] {{quarter_f[42].team_name}}
            - else
              span[] {{quarter_f[42].team_name}}
      div
        .bracketbox
          span.info (47)2 July – Bordeaux
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(47, quarter_f[41].team_id, quarter_f[41].team_name)"] {{quarter_f[41].team_name}}
            - else
              span[] {{quarter_f[41].team_name}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(47, quarter_f[43].team_id, quarter_f[43].team_name)"] {{quarter_f[43].team_name}}
            - else
              span[] {{quarter_f[43].team_name}}
      div
        .bracketbox
          span.info (48)3 July – Saint-Denis
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(48, quarter_f[40].team_id, quarter_f[40].team_name)"] {{quarter_f[40].team_name}}
            - else
              span[] {{quarter_f[40].team_name}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_sf(48, quarter_f[44].team_id, quarter_f[44].team_name)"] {{quarter_f[44].team_name}}
            - else
              span[] {{quarter_f[44].team_name}}



    .r3
      div
        .bracketbox
          span.info (49)6 July – Lyon
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_f(49, semi_f[45].team_id, semi_f[45].team_name)"] {{semi_f[45].team_name}}
            - else
              span[]{{semi_f[45].team_name}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_f(49, semi_f[46].team_id, semi_f[46].team_name)"] {{semi_f[46].team_name}}
            - else
              span[]{{semi_f[46].team_name}}
      div
        .bracketbox
          span.info (50)7 July – Marseille
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_f(50, semi_f[47].team_id, semi_f[47].team_name)"] {{semi_f[47].team_name}}
            - else
              span[]{{semi_f[47].team_name}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="go_through_f(50, semi_f[48].team_id, semi_f[48].team_name)"] {{semi_f[48].team_name}}
            - else
              span[]{{semi_f[48].team_name}}



    .r4
      div
        .bracketbox
          span.info (51)10 July – Saint-Denis
          span.teama
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="win(finalists[49].team_id, finalists[49].team_name)"] {{finalists[49].team_name}}
            - else
              span[]{{finalists[49].team_name}}
          span.teamb
            - if current_user.id == 1
              a[href='javascript:void(0);' ng-click="win(finalists[50].team_id, finalists[50].team_name)"] {{finalists[50].team_name}}
            - else
              span[]{{finalists[50].team_name}}




    .r5
      .final
        .bracketbox
          span.teamc
            strong
              h3
                | {{champion.team_name}}

app/views/predictions/_match_predictions.slim
table.table-standard.table.table-bordered.table-striped.table-condensed.matches-predictions[style='width:520px']
  tr
    th Kick-off
    th[style='text-align:right'] Host
    th Score
    th Guest
    tr[ng-repeat="match in groups['#{group.name}'].matches"]
      td[style='height:20px;width:100px'] {{ match.start_at | date : 'dd MMM HH:mm'}}
      td[style='height:20px;width:120px;text-align:right']
        | {{ match.host_team}}
        span.flag_16.right_16[ng-class="{'{{match.host_flag}}_16_right' : true}"]
      td[style='height:20px;width:120px;text-align:center']
        - if current_user.id == 1
          select[ng-model="match.host_prediction" ng-options="item for item in #{(0..8).to_a}" ng-change="predictMatch(match)"]
            option value="" &nbsp;
        - else
          span[] {{match.host_prediction}}
        | &nbsp;&nbsp;:&nbsp;&nbsp;
        - if current_user.id == 1
          select[ng-model="match.guest_prediction" ng-options="item for item in #{(0..8).to_a}" ng-change="predictMatch(match)"]
            option value="" &nbsp;
        - else
          span[] {{match.guest_prediction}}
      td[style='height:20px;width:120px']
        span.flag_16.left_16[ng-class="{'{{match.guest_flag}}_16_left' : true}"]
        | {{ match.guest_team}}

app/views/predictions/_third_placed_teams.slim
table.table-standard.table.table-bordered.table-condensed.standings-predictions[style='width:520px']
  tr
    th rel="tooltip" data-container="body" data-original-title='Position' Pos
    th Group
    th Team
    th rel="tooltip" data-container="body" data-original-title='Played' Pld
    th rel="tooltip" data-container="body" data-original-title='Wins' W
    th rel="tooltip" data-container="body" data-original-title='Draws' D
    th rel="tooltip" data-container="body" data-original-title='Loses' L
    th rel="tooltip" data-container="body" data-original-title='Goals For' GF
    th rel="tooltip" data-container="body" data-original-title='Goals Against' GA
    th rel="tooltip" data-container="body" data-original-title='Goal Difference' GD
    th rel="tooltip" data-container="body" data-original-title='Points' Pts

    tr[ng-repeat="team in third_placed_teams | toArray | orderBy : ['-points', '-goal_difference', '-goals_for', '-coef']" ng-class="{'qualifies' : $index < 4}"]
      td[style='height:20px;width:60px'] {{$index + 1}}
      td[style='height:20px;width:60px'] {{team.group}}
      td[style='height:20px;width:200px']
        span.flag_16.left_16[ng-class="{'{{team.flag}}_16_left' : true}"]
        | {{team.name}}
      td[style='height:20px;width:60px'] {{team.matches_played}}
      td[style='height:20px;width:60px'] {{team.matches_won}}
      td[style='height:20px;width:60px'] {{team.matches_drawn}}
      td[style='height:20px;width:60px'] {{team.matches_lost}}
      td[style='height:20px;width:60px'] {{team.goals_for}}
      td[style='height:20px;width:60px'] {{team.goals_against}}
      td[style='height:20px;width:60px'] {{team.goal_difference}}
      td[style='height:20px;width:60px'] {{team.points}}

p
  | The four best third-placed teams are determined according to the following criteria:
  ol
    li Higher number of points obtained
    li Superior goal difference
    li Higher number of goals scored
    li Position in the UEFA national team coefficient ranking system

app/views/predictions/_top_scorer_prediction.slim
br
- if current_user.id ==  1
  = form_tag top_scorer_prediction_path, remote: true, method: :post
   = text_field_tag :name, current_user.top_scorer_prediction.try(:name)
   br
   br
   button.btn-lg.btn-primary.pull-left SAVE
- else
  = current_user.top_scorer_prediction.try(:name)
br
br
hr
p * If two or more players have scored an equal amount of goals, each participant will be awarded points for the player in question.

app/views/predictions/index.slim
.tabbable[ng-controller='predictions']
  ul.nav.nav-tabs
    li.active
      a[href="#groups" data-toggle='tab'] Group stage
    li
      a[href="#eliminations" data-toggle='tab' ng-click='populateKnockoutStage()'] Knockout stage
    li
      a[href="#top_scorer" data-toggle='tab'] Top scorer
  .tab-content[style="padding-top:10px"]
    .tab-pane.active#groups
      .tabbable
        ul.nav.nav-pills#groups-nav
          - @groups.each do |group|
            li[ng-class="{'active' : current_group == '#{group.name}'}"]
              a[href="#group#{group.name}" data-toggle='tab' ng-click="current_group='#{group.name}';"] = group.name
          li[ng-class="{'active': current_group == '3rd'}"]
            a[href="#3rd-placed" data-toggle='tab' ng-click="current_group='3rd';"] Third-placed teams
        .tab-content
          - @groups.each do |group|
            .tab-pane[id="group#{group.name}" ng-class="{'active': current_group == '#{group.name}'}"]
              = render 'predictions/match_predictions', group: group
              = render 'predictions/group_standing_predictions', group: group
          .tab-pane#3rd-placed[ng-class="{'active': current_group == '3rd'}"]
            = render 'predictions/third_placed_teams'
    .tab-pane#eliminations
      = render 'predictions/knockout_stage_predictions'
    .tab-pane#top_scorer
      = render 'predictions/top_scorer_prediction'
